---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/braindrOverview/braindrOverview.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/6245/articles/292763/master/folder/figures/braindrOverview"
    url: "/users/6245/articles/292763/master/file/figures/braindrOverview/braindrOverview.png"
